exports.INCREMENT_COUNTER = 'INCREMENT_COUNTER';
exports.DECREMENT_COUNTER = 'DECREMENT_COUNTER';

// Auth
exports.SIGN_IN = 'SIGN_IN';
exports.SIGN_UP = 'SIGN_UP';
exports.UPDATE_SIGN_IN_DETAILS = 'UPDATE_SIGN_IN_DETAILS'

// Companies
exports.GET_COMPANIES = 'GET_COMPANIES';
